objects/Configure_House__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Anniversary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Anniversary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Birthday__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Birthday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ExpenseItemTable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ExpenseItemTable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ExpenseTable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ExpenseTable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HouseTable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HouseTable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>House_Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>House Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inaugration_Date__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inaugration Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MemberTable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MemberTable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PersonTable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PersonTable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>This_Year_Balance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>This Year Balance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Total_Member</label>
        <type>Checkbox</type>
    </fields>
    <label>Configure House</label>
</CustomObject>

objects/Expense__c.object
<CustomObject>
    <description>This object hold the expense details.</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Check Status of expense</description>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Available_Balance__c</fullName>
        <description>This field will calculate the  Balance Available..Calculated By differnce of Total Balance and Total Expense</description>
        <formula>Total_Balance__c - Total_Expense__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>From this we have to choose the Member Whose Expense We are holding</description>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Balance__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total Balance For one Member</description>
        <inlineHelpText>This field will holds the total balance for member</inlineHelpText>
        <label>Total Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>It is Picklist where we have to select the yearly or Monthly</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Expense_Item__c.object
<CustomObject>
    <description>This object hold the expense details.</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>used to check the status of expense item Amount</description>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expense_Amount__c</fullName>
        <description>It will Holds the Expenses Price</description>
        <label>Expense Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expense_Type__c</fullName>
        <description>It holds the Picklist in hich we have ddifferent types of Expenses</description>
        <label>Expense Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <description>This will choose the Expense from Expenses</description>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Expense Items</relationshipLabel>
        <relationshipName>Expense_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Expense Items</relationshipLabel>
        <relationshipName>Expense_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expense Item</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/House__c.object
<CustomObject>
    <description>Holds details Regarding House about Owner ,Where it is located and Everything related to a house.</description>
    <fields>
        <fullName>Address__c</fullName>
        <description>It will Hold Address of House.</description>
        <inlineHelpText>To hold the address of house</inlineHelpText>
        <label>Address</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email Address</description>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>House_owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>It will Hold same name Of Member ..It is a lookup field.</description>
        <inlineHelpText>Hold the owner</inlineHelpText>
        <label>House owner</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Houses</relationshipLabel>
        <relationshipName>Houses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>This_Year_Balance__c</fullName>
        <description>Total  sum of Balance from all Member</description>
        <inlineHelpText>This field will hold the Sum of balance from all the members. Populated via trigger.</inlineHelpText>
        <label>This Year Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Balance__c</fullName>
        <label>Total_Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>House</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Houses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Member__c.object
<CustomObject>
    <description>This object holds the members details under the house.</description>
    <fields>
        <fullName>Anniversary__c</fullName>
        <description>It will holds Anniversary of Person.</description>
        <formula>Person__r.Anniversary__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Will grab value from Person Anniversary field</inlineHelpText>
        <label>Anniversary</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Birthday__c</fullName>
        <description>It will holds the date of the Person Birthday</description>
        <formula>Person__r.Birthday__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Will grab value from Person Birthday field</inlineHelpText>
        <label>Birthday</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>House__c</fullName>
        <description>From This we have to choose the House Details of member.</description>
        <inlineHelpText>Not reparenting allowed</inlineHelpText>
        <label>House</label>
        <referenceTo>House__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <description>From this we Will Choose Person</description>
        <inlineHelpText>Allow reparenting</inlineHelpText>
        <label>Person</label>
        <referenceTo>Person__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>This_Year_Balance__c</fullName>
        <description>Total Balance from all  the Expense</description>
        <inlineHelpText>This field will hold the Sum of balance from all the Expenses.
Populated via trigger</inlineHelpText>
        <label>This Year Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Person__c.object
<CustomObject>
    <description>Holds the individual Person details.</description>
    <fields>
        <fullName>Anniversary__c</fullName>
        <description>Anniversary date Of the Person.</description>
        <inlineHelpText>This field is used to send anniversary notifications.</inlineHelpText>
        <label>Anniversary</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Birthday__c</fullName>
        <description>Hold Birthday of the person</description>
        <inlineHelpText>This field is used to send b’day notifications</inlineHelpText>
        <label>Birthday</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Emai of person</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Holds the Gender of person</description>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Person Contact Number</description>
        <inlineHelpText>Will Hold  Phone Number</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>This_Year_Balance__c</fullName>
        <description>Hold Total balance from  the member</description>
        <inlineHelpText>This field will hold the Sum of balance from all the members. Populated via trigger</inlineHelpText>
        <label>This Year Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Person</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HouseMemberWrapperDisplayController.cls
/**
* Purpose      :  It is a controller class used in lightning component.
* 
* Created By   :  Shubh Shree Rathore
* 
* Created Date :  30/06/2019
* 
* Revision Logs:  V1.0 -  Shubh Shree Rathore - 30/06/2019- Created
* 
**/

public class HouseMemberWrapperDisplayController {
    @AuraEnabled
    public static String createRecord(House__c house) {
        
        try {
            if(house !=NULL && String.isNotBlank(house.Address__c) && String.isNotBlank(house.Email__c)) {
                  insert house;
                 return 'Success';
            }
          } 
        catch(Exception ex) {
           return ex.getMessage();
        }
        return 'Success';
    }  
    @AuraEnabled
    public static String createMemberRecord(Member__c member){
         String msg ; 
        try{ 
            if(member !=NULL && String.isNotBlank(member.House__c) && String.isNotBlank(member.Person__c)) {
                 insert member;
                msg= 'Success';
            }
        }
       	             
        catch(Exception ex){
            system.debug(ex.getMessage());
            msg= ex.getMessage();
        }
        return msg;
    }
    
    @AuraEnabled
    public static HouseMemberController initMethod() {
        HouseMemberController returnwrapperClass = new  HouseMemberController();        
        returnwrapperClass.houseRec = [SELECT Name,Total_Balance__c,Address__c ,Email__c FROM House__c order by CreatedDate desc LIMIT 5 ];
        returnwrapperClass.memberRec = [SELECT Name,Birthday__c,Anniversary__c ,House__c,Person__c FROM Member__c order by CreatedDate desc LIMIT 5];
        returnwrapperClass.personRec = [SELECT Name,Phone__c,Email__c,Gender__c FROM Person__c ];
        returnwrapperClass.expenseRec = [SELECT Name,Type__c,Available_Balance__c,Approval_Status__c FROM Expense__c where Type__c ='Yearly'];
        returnwrapperClass.expenseItemRec = [SELECT Name,Expense_Amount__c,Approval_Status__c,Expense_Type__c FROM Expense_Item__c ];
        returnwrapperClass.customFields =[Select HouseTable__c,	ExpenseItemTable__c,ExpenseTable__c,House_Owner__c,
                                          Birthday__c,Anniversary__c,Inaugration_Date__c,MemberTable__c,PersonTable__c,This_Year_Balance__c,Total_Member__c 
                                          FROM Configure_House__c];
        
        for(Configure_House__c ins :returnwrapperClass.customFields ){
            returnwrapperClass.checkHouse = ins.HouseTable__c;
            returnwrapperClass.checkMember = ins.MemberTable__c;
            returnwrapperClass.checkPerson =ins.PersonTable__c;
            returnwrapperClass.checkExpense =ins.ExpenseTable__c;
            returnwrapperClass.checkExpenseItem =ins.ExpenseItemTable__c;
            returnwrapperClass.checkhousefield1 =ins.House_Owner__c;
            returnwrapperClass.checkhousefield2 =ins.Inaugration_Date__c;
            returnwrapperClass.checkhousefield3 =ins.Total_Member__c ;
            returnwrapperClass.checkhousefield4 =ins.This_Year_Balance__c;
            returnwrapperClass.checkmemberfield1 =ins.Birthday__c;
            returnwrapperClass.checkmemberfield2 =ins.Anniversary__c;
        }
        return returnwrapperClass; 
    }
    
    public class HouseMemberController {
        @AuraEnabled public List<House__c> houseRec{get;set;}
        @AuraEnabled public List<Member__c> memberRec{get;set;}
        @AuraEnabled public List<Person__c> personRec{get;set;}
        @AuraEnabled public List<Expense__c> expenseRec{get;set;}
        @AuraEnabled public List<Expense_Item__c> expenseItemRec{get;set;}
        @AuraEnabled public List<Configure_House__c> customFields{get;set;}
        @AuraEnabled public boolean checkHouse {get;set;}
        @AuraEnabled public boolean checkMember {get;set;}
        @AuraEnabled public boolean checkPerson {get;set;}
        @AuraEnabled public boolean checkExpense {get;set;}
        @AuraEnabled public boolean checkExpenseItem {get;set;}
        @AuraEnabled public boolean checkhousefield1 {get;set;}
        @AuraEnabled public boolean checkhousefield2 {get;set;}
        @AuraEnabled public boolean checkhousefield3 {get;set;}
        @AuraEnabled public boolean checkhousefield4 {get;set;}
        @AuraEnabled public boolean checkmemberfield1 {get;set;}
        @AuraEnabled public boolean checkmemberfield2 {get;set;}
    }
    
}