objects/Expense__c.object
<CustomObject>
    <description>This object hold the expense details.</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>Check Status of expense</description>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>From this we have to choose the Member Whose Expense We are holding</description>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Expense__c</fullName>
        <description>When we are selecting Type as Yearly it will Calculate the Expense from Child Line Item.
When we are selecting Type as Monthly it will Calculate the Expense from Child Expense Item.</description>
        <inlineHelpText>This field will auto populate according to child expenses or expenses line items.</inlineHelpText>
        <label>Total Expense</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>It is Picklist where we have to select the yearly or Monthly</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Yearly_Expense__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>When Type is yearly then it is going to use</description>
        <inlineHelpText>Will come in picture
when Type is Monthly</inlineHelpText>
        <label>Yearly Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Expense_Item__c.object
<CustomObject>
    <description>This object hold the expense details.</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>used to check the status of expense item Amount</description>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reject</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <description>This Field is holding Bill no. having unique values..</description>
        <label>Bill_Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This will Hold the Date When A item is purchased</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>This will Holds the Description of the item</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expense_Amount__c</fullName>
        <description>It will Holds the Expenses Price</description>
        <label>Expense Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expense_Type__c</fullName>
        <description>It holds the Picklist in hich we have ddifferent types of Expenses</description>
        <label>Expense Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <description>This will choose the Expense from Expenses</description>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Expense Items</relationshipLabel>
        <relationshipName>Expense_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Expense Items</relationshipLabel>
        <relationshipName>Expense_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expense Item</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/House__c.object
<CustomObject>
    <description>Holds details Regarding House about Owner ,Where it is located and Everything related to a house.</description>
    <label>House</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Houses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Member__c.object
<CustomObject>
    <description>This object holds the members details under the house.</description>
    <fields>
        <fullName>House__c</fullName>
        <description>From This we have to choose the House Details of member.</description>
        <inlineHelpText>Not reparenting allowed</inlineHelpText>
        <label>House</label>
        <referenceTo>House__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/HouseDetailPageController.cls
/**
* Purpose      :  It is a controller class used in lightning component.
* 
* Created By   :  Shubh Shree Rathore
* 
* Created Date :  28/05/2019
* 
* Revision Logs:  V1.0 -  Shubh Shree Rathore - 28/05/2019- Created
* 
**/

public class HouseDetailPageController {
/**
* @description    :	This method is used to fetch the data of member which is associated to a particular house.
*     
* @args           :	Id
*   
* @return         :	list of member object.
*      
* @revision Logs  :	V1.0 - Shubh Shree Rathore  - 28/06/2019- Created
*     
**/  

@AuraEnabled
    public static ResponeUtility getDoInit(String houseId) {
       ResponeUtility respone = new ResponeUtility();
        try{
             List<Member__c> member = [SELECT Id, name FROM Member__c WHERE House__c =: houseId]; 
             respone.setBody(member);
         }
       	    Catch(Exception ex) {
            respone.setError(ex.getMessage());
         }
       return respone;
    } 
    
/**
* @description    :	This method is used to fetch the data of expense whose type is yearly
*     
* @args           :	Id
*   
* @return         :	list of expense object
*      
* @revision Logs  :	V1.0 - Shubh Shree Rathore  - 28/06/2019- Created
*     
**/
    
    @AuraEnabled
    public static ResponeUtility getExpenseYearly(Id memId) {
         ResponeUtility respone = new ResponeUtility();
        try {
            List<Expense__c> yearlyExpense = [SELECT Id, Name,Total_Expense__c FROM Expense__c WHERE Member__c =: memId AND Type__c ='Yearly'];  
            respone.setBody(yearlyExpense);
         }
       	    Catch(Exception ex) {
            respone.setError(ex.getMessage());
         }
       return respone;
    }
    
/**
* @description    :	This method is used to fetch the data of expense whose type is monthly.
*     
* @args           :	Id
*   
* @return         :	list of expense object
*      
* @revision Logs  :	V1.0 - Shubh Shree Rathore  - 28/06/2019- Created
*     
**/
    
     @AuraEnabled
    public static ResponeUtility getExpenseMonthly(Id yearExp) {
        ResponeUtility respone = new ResponeUtility();
       try {
        	List<Expense__c>   monthlyExpense= [SELECT Id, Name FROM Expense__c WHERE Yearly_Expense__c =: yearExp AND Type__c ='Monthly']; 
            respone.setBody(monthlyExpense);
        }
       	    Catch(Exception ex) {
            respone.setError(ex.getMessage());
        }
       return respone;
    }         
    
/**
* @description    :	This method is used to fetch the data of expense item 
*     
* @args           :	Id
*   
* @return         :	list of expense item object
*      
* @revision Logs  :	V1.0 - Shubh Shree Rathore  - 30/06/2019- Created
*     
**/
     @AuraEnabled
    public static ResponeUtility getExpenseItem(Id expId) {
        ResponeUtility respone = new ResponeUtility();
       try {
        	List<Expense_Item__c>   expenseItems = [SELECT Id, Name,Date__c,Expense_Type__c,Description__c,Expense_Amount__c,Expense__c,
                                                    Bill_Number__c,Approval_Status__c FROM Expense_Item__c  WHERE Expense__c =: expId];  
            respone.setBody(expenseItems);
         }
       	    Catch(Exception ex) {
            respone.setError(ex.getMessage());
         }
       return respone;
  
   } 
}