objects/Expense__c.object
<CustomObject>
    <description>This object hold the expense details.</description>
    <fields>
        <fullName>Type__c</fullName>
        <description>It is Picklist where we have to select the yearly or Monthly</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <label>Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Expense_Item__c.object
<CustomObject>
    <description>This object hold the expense details.</description>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <description>This Field is holding Bill no. having unique values..</description>
        <label>Bill_Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This will Hold the Date When A item is purchased</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>This will Holds the Description of the item</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expense_Amount__c</fullName>
        <description>It will Holds the Expenses Price</description>
        <label>Expense Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <description>This will choose the Expense from Expenses</description>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Expense Items</relationshipLabel>
        <relationshipName>Expense_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expense Item</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_ExpenseItemTrigger.cls
/**
*   Description 	:   	This class is used to test the expense item trigger.
*
*   Created by      :   	Shubh Shree Rathore
*
*   Created Date    :   	08/06/2019
*
*   Revision Log    :  	    V_1.0 - Created
*
*	Coverage		: 	
**/

@isTest
private class Test_ExpenseItemTrigger {
/* 
*	Description		:	This method delete the expense when expense items are associated with it. 
*
*	@argument		:	none
*
*	Revision Logs	: 	V_1.0 - Created
*/
    
 @isTest  static  void testbillNoUnique() {
     
        //Inserting the expense 
        Expense__c exp = new  Expense__c(name='Test',Type__c='Monthly');
        insert exp;
        Expense__c exp1 = new  Expense__c(name='Test',Type__c='Monthly');
     	insert exp1;
     
        //Inserting the multiple expense item on that expense with samr bill number .
         List<Expense_Item__c> expenseItem = new List<Expense_Item__c>();
       	 Expense_Item__c expItem;
     
         expItem = new Expense_Item__c(Expense__c =exp.Id,Date__c=date.today(),
                                                      Bill_Number__c='1009',Expense_Amount__c =0, Description__c ='test');
     	 expItem = new Expense_Item__c(Expense__c =exp.Id,Date__c=date.today(),
                                                      Bill_Number__c='1009',Expense_Amount__c =0, Description__c ='test');
     
         expItem = new Expense_Item__c(Expense__c =exp1.Id,Date__c=date.today(),
                                                      Bill_Number__c='1009',Expense_Amount__c =0, Description__c ='test');
          
     	expenseItem.add(expItem);
        insert expenseItem;
     
        //Perform test
     
        Test.startTest();
        try {
            system.debug('expense'+expenseItem);
        } catch (Exception ex) {
              //According to trigger it should give the below error message.
			System.assertNotEquals(true, ex.getMessage().contains('Bill Number Cannot be Duplicate')); 
        }
        Test.stopTest();
       
    }
}