objects/House__c.object
<CustomObject>
    <description>Holds details Regarding House about Owner ,Where it is located and Everything related to a house.</description>
    <fields>
        <fullName>Address__c</fullName>
        <description>It will Hold Address of House.</description>
        <inlineHelpText>To hold the address of house</inlineHelpText>
        <label>Address</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email Address</description>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>House_owner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>It will Hold same name Of Member ..It is a lookup field.</description>
        <inlineHelpText>Hold the owner</inlineHelpText>
        <label>House owner</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Houses</relationshipLabel>
        <relationshipName>Houses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>House</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Houses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HouseController.cls
/**
* Purpose      :  It is a controller class used in lightning component.
* 
* Created By   :  Shubh Shree Rathore
* 
* Created Date :  28/06/2019
* 
* Revision Logs:  V1.0 -  Shubh Shree Rathore - 28/06/2019- Created
* 
**/

public class HouseController {
/**
* @description    :	This method is used to fetch the data of house of five top created.
*     
* @args           :	None
*   
* @return         :	list  list of house
*      
* @revision Logs  :	V1.0 - Shubh Shree Rathore  - 28/06/2019- Created
*     
**/      
  @AuraEnabled
    public static List<House__c> fetchHouse(){
        return [SELECT Name,House_owner__c,Address__c ,Email__c FROM House__c order by CreatedDate desc LIMIT 5  ];
    }
/**
* @description    :	This method is used to save the records.
*     
* @args           :	String
*   
* @return         :	String
*      
* @revision Logs  :	V1.0 - Shubh Shree Rathore  - 28/06/2019- Created
*     
**/    
    
    @AuraEnabled
    public static String saveRecords(String houseName,String houseEmail,String houseOwner,String houseAddress) {
        
        House__c house = new House__c();
        house.Name = houseName;
        house.Email__c = houseEmail;
        house.House_owner__c = (Id)houseOwner;
        house.Address__c = houseAddress;
        insert house;
        return 'Success'; 
    }
    
}