objects/Person__c.object
<CustomObject>
    <description>Holds the individual Person details.</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Emai of person</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Next_Anniversary__c</fullName>
        <description>Next Anniversary Calculation</description>
        <formula>IF(MONTH(Anniversary__c)&gt;MONTH(TODAY()),DATE(YEAR(TODAY()),MONTH(Anniversary__c),DAY(Anniversary__c)),
IF(MONTH(Anniversary__c)&lt;MONTH(TODAY()),DATE(YEAR(TODAY())+1,MONTH(Anniversary__c),DAY(Anniversary__c)),
IF(DAY(Anniversary__c) &gt;= (DAY(TODAY())),DATE(YEAR(TODAY()),MONTH(Anniversary__c),DAY(Birthday__c)),
DATE(YEAR(TODAY())+1,MONTH(Anniversary__c),DAY(Anniversary__c)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Next Anniversary</label>
        <type>Date</type>
    </fields>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Person</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BatchAnniversaryAlert.cls
/**
* Purpose      :  It is a Batch class used to Send Anniversary Email Alert 
*
* Created By   :  Shubh Shree Rathore
* 
* Created Date :  05/06/2019
* 
* Revision Logs:  V1.0 -  Shubh Shree Rathore - 05/06/2019- Created
* 
**/
global class BatchAnniversaryAlert implements Database.Batchable <sObject> ,Database.Stateful {

    // List To store Email Address  
    global List<String> emailStore =  new List<String>();

/**
* @description    :   This method is used to Start the Batch 
*     
* @args           :  Database.BatchableContext
*   
* @return         :   void
*      
* @revision Logs  :   V1.0 - Shubh Shree Rathore  - 1/05/2019- Created
*     
**/ 
    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        //returning a list of Person anniversary whose Email are not Blank
        return Database.getQueryLocator('SELECT ID,Next_Anniversary__c,Email__c FROM Person__c WHERE Email__c != NULL');
        
    }

/**
* @description    :   This method is used to Execute the Batch. In Execute method we will check the Person whose anniversary is Today
*     
* @args           :  Database.BatchableContext
*   
* @return         :   void
*      
* @revision Logs  :   V1.0 - Shubh Shree Rathore  - 1/05/2019- Created
*     
**/    
   
    global void execute(Database.BatchableContext bc, List<Person__c> recordsOfAnniversary ){
        
        //This returnTodaysDate will hold today's date 
        Date returnTodaysDate = system.today();
        
        //Loop To check whose anniversary is today
        For(Person__c anniversary : recordsOfAnniversary){
            if(anniversary.Next_Anniversary__c == returnTodaysDate ) {
                
                //Storing today's anniversary's Email in List.
                emailStore.add(anniversary.Email__c);
            }
        }
    }    
/**
* @description		:	This method is used to Finish the Batch.This will send Mail to every person whose email are in the list
*
* @args     		:  	Database.BatchableContext
*   
* @return      		:   void
*      
* @revision Logs 	:   V1.0 - Shubh Shree Rathore  - 1/05/2019- Created
*     
**/
    
    global void finish(Database.BatchableContext bc){
        //checking size of Email List
        if(emailStore.size()>0){
            //Sending Single Message to Everyone
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.toaddresses= emailStore;
            mail.Subject='Anniversary Wishes';
            mail.plaintextbody='Wish You a Very Happy Anniversary';
            Messaging.SingleEmailMessage[] msgs = new list <Messaging.SingleEmailMessage> {mail};
                Messaging.sendEmailResult[] sendingEmail = Messaging.sendEmail(msgs);
        }
    }    
}