objects/Person__c.object
<CustomObject>
    <description>Holds the individual Person details.</description>
    <fields>
        <fullName>Birthday__c</fullName>
        <description>Hold Birthday of the person</description>
        <inlineHelpText>This field is used to send b’day notifications</inlineHelpText>
        <label>Birthday</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>SMS_Body__c</fullName>
        <label>SMS Body</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Send_SMS_Status__c</fullName>
        <label>Send SMS Status</label>
        <picklist>
            <picklistValues>
                <fullName>Send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Send_SMS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send SMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Twilio_Response__c</fullName>
        <label>Twilio Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Person</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestSendSms.cls
@isTest
public class TestSendSms {

   @isTest static void testprocessSmsSuccess() {
        Test.startTest();
        Person__c per = new Person__c();
        per.Name='Abc';
        per.Birthday__c= System.today();
        per.Mobile__c ='+919001811457';
        per.Send_SMS__c =true;
        per.SMS_Body__c ='test';
        insert per;
        Test.setMock(HttpCalloutMock.class, new TestsendSmsWithTwilioSuccess()); 
         Test.stopTest();
       Person__c persons = [SELECT ID, Send_SMS_Status__c,Twilio_Response__c From Person__c Where  id =:per.Id];
       system.assertEquals('Send',persons.Send_SMS_Status__c);
        //system.assertEquals(,persons.Twilio_Response__c);
    }
    @isTest static void testprocessSmsFailure() {
        Test.startTest();
        Person__c per = new Person__c();
        per.Name='Abcd';
        per.Mobile__c ='+91900181147';
        per.Birthday__c= System.today();
        per.Send_SMS__c =true;
        per.SMS_Body__c ='test';
        insert per;
        Test.setMock(HttpCalloutMock.class, new TestsendSmsWithTwilioFailure()); 
        Test.stopTest();
         Person__c persons = [SELECT ID, Send_SMS_Status__c,Twilio_Response__c From Person__c Where  id =:per.Id];
       system.assertEquals('Error',persons.Send_SMS_Status__c);
    }
}