objects/Person__c.object
<CustomObject>
    <description>Holds the individual Person details.</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Emai of person</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>This_Year_Expense__c</fullName>
        <description>Total Sum of all Expenses of whole year  From Member</description>
        <inlineHelpText>This field will hold the Sum of expenses from all the members.Populated via trigger</inlineHelpText>
        <label>This Year Expense</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Person</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/YearlyExpenseToHouseOwner.cls
global class YearlyExpenseToHouseOwner implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext bc){
          return Database.getQueryLocator('SELECT ID,House_Owner__c.person__r.Email__c,	This_Year_Expense__c from Person__c Where Email__c != Null');
      } 
    global void execute(Database.BatchableContext bc, List<Person__c> recOfPerson) {
        
    }
    global void finish(Database.BatchableContext bc) {
        
    }
}